### ISSUE TITLE
Isue with mysql value vehicles

### ISSUE THREAD

**Issue by saulienis** [adikanchukov/los-santos-v#10]
[ERROR] [MySQL] An error happens on MySQL for query “UPDATE Players SET SkinModel=DEFAULT, Weapons=DEFAULT, Vehicle=DEFAULT, Cash=DEFAULT, Experience=DEFAULT, Prestige=Prestige + 1 WHERE PlayerID=@playerId {@playerId=license:ee58b3f2fc517d232b817cf164beb99d9e3b8cd3}”: Field ‘Vehicle’ doesn’t have a default value

Tried adding a table with Vehicles. But doesnt help, dont really know the defaukt value of vehicles.

**Comment by omershevach** [comment]
In [los-santos-v]\lsv-main\modules\server\db.lua
change rows 64 - 69 to:
```
function Db.UpdatePrestige(player, callback)
	MySQL.Async.execute('UPDATE Players SET SkinModel=DEFAULT, Weapons=DEFAULT, Cash=DEFAULT, Experience=DEFAULT, Prestige=Prestige + 1 WHERE PlayerID=@playerId',
			{ ['@playerId'] = Scoreboard.GetPlayerIdentifier(player) }, function()
				if callback then callback() end
	end)
end
```

**Comment by saulienis** [comment]
> In [los-santos-v]\lsv-main\modules\server\db.lua
> change rows 64 - 69 to:
> 
> ```
> function Db.UpdatePrestige(player, callback)
> 	MySQL.Async.execute('UPDATE Players SET SkinModel=DEFAULT, Weapons=DEFAULT, Cash=DEFAULT, Experience=DEFAULT, Prestige=Prestige + 1 WHERE PlayerID=@playerId',
> 			{ ['@playerId'] = Scoreboard.GetPlayerIdentifier(player) }, function()
> 				if callback then callback() end
> 	end)
> end
> ```

So with this it will ignore the vehicles right? Will it actuqlly save them though? Wont they have to buy the cars again after prestige?

**Comment by warxander** [comment]
Also, execute this in your database:
`UPDATE Players DROP COLUMN Vehicle;`

Because the latest LSV version is no longer using permanent Personal Vehicles.

**Comment by saulienis** [comment]
Hi,sorry for taking so long, had a busy week of work haha, tried the update MySQL function,using phpMyAdmin  (MariaDB),got this

`Static analysis:
5 errors were found during analysis.

A new statement was found, but no delimiter between it and the previous one. (near "UPDATE" at position 35)
A new statement was found, but no delimiter between it and the previous one. (near "DROP" at position 50)
An expression was expected. (near "COLUMN" at position 55)
Unrecognized keyword. (near "COLUMN" at position 55)
Unexpected token. (near "Vehicle" at position 62)

SQL query:  
SELECT * FROM `Players` WHERE 1 UPDATE Players DROP COLUMN Vehicle 
MySQL said:  
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE Players DROP COLUMN Vehicle' at line 3
`
as far as i understand,it doesnt understand this command, tried something similar 
`ALTER TABLE Players
DROP Vehicle;`

`SQL query: 

ALTER TABLE Players
DROP Vehicle

MySQL said:  
#1091 - Can't DROP COLUMN `Vehicle`; check that it exists`

any ideas would be greatly apreciated

**Comment by warxander** [comment]
1. Replace `Db.UpdatePrestige` function with the one from above.
2. Execute `UPDATE Players DROP COLUMN Vehicle;` in your SQL database.

You don't need anything else.
