### ISSUE TITLE
Issue with velocity mission

### ISSUE THREAD

**Issue by saulienis** [adikanchukov/los-santos-v#12]
After finishing Velocity mission, the rocket voltic doesn't explode.
I believe this is the code for the car to explode when the mission is finished.

`RegisterNetEvent('lsv:velocityFinished')
AddEventHandler('lsv:velocityFinished', function(success, reason)
	if helpHandler then helpHandler:Cancel() end

	MissionManager.FinishMission(success)

	if not HasSoundFinished(detonationSound) then StopSound(detonationSound) end
	ReleaseSoundId(detonationSound)
	detonationSound = nil

	if not success and not IsPedInVehicle(PlayerPedId(), vehicle, false) then
		SetEntityAsMissionEntity(vehicle, true, true)
		DeleteVehicle(vehicle)
	end
	vehicle = nil

	RemoveBlip(vehicleBlip)
	vehicleBlip = nil

	Gui.FinishMission('Velocity', success, reason)
end)
`

**Comment by warxander** [comment]
It shouldn't explode by game design.
