### ISSUE TITLE
the problem of the garage

### ISSUE THREAD

**Issue by IvlevAleksandr** [adikanchukov/los-santos-v#17]
Hello! Installed your server. I have a problem after buying a garage. The personal menu is empty and near the garage.
![1](https://user-images.githubusercontent.com/57568939/85026196-d0d1b500-b191-11ea-85f6-1e975a5c38b3.jpg)
![2](https://user-images.githubusercontent.com/57568939/85026216-d5966900-b191-11ea-9546-3cdb0d7ef8ba.jpg)

**Comment by warxander** [comment]
Garage doesn't contain vehicles by default.
You need to do Vehicle Import missions to get vehicles.

**Comment by IvlevAleksandr** [comment]
Thanks! Great job! Sorry to bother you!
