### ISSUE TITLE
One on One Deathmatch

### ISSUE THREAD

**Issue by IvlevAleksandr** [adikanchukov/los-santos-v#18]
Hello! I noticed a problem in the one on One Deathmatch duel. After 5 wins, player 1 wins and the money is transferred to him. But then if player 1 is killed by the losing player 2, the One on One Deathmatch continues for player 2 until he wins. In this case, the winning player 1 by killing player 2 the score is 4, the interface is displayed only for player 2. After player 2 wins the One on One Deathmatch ends, the money is transferred back to player 2.
![1](https://user-images.githubusercontent.com/57568939/85220510-64d79280-b3c5-11ea-9e0c-91c5bbc86848.jpg)

**Comment by warxander** [comment]
One on One Deathmatch was removed.
