### ISSUE TITLE
Double chat

### ISSUE THREAD

**Issue by HK1GTARP** [adikanchukov/los-santos-v#25]
Is this a feature or not? 
Sorry, i'm a new developer :(
![image](https://user-images.githubusercontent.com/74354832/99404035-116d6000-28e3-11eb-9c95-7a52c3d0cfe7.png)

**Comment by warxander** [comment]
Hi!

No, it shouldn't happen.
Did you modify loading resources list in `server.cfg`?

**Comment by HK1GTARP** [comment]
i see this after i tried to added a custom font for warmenu and update fiveM installer :D

**Comment by HK1GTARP** [comment]
you can see chat input now have "[" and "]". It come from new update of fiveM o.o

**Comment by warxander** [comment]
You shouldn't use any of FiveM resources from `cfx-server-data`.
