### ISSUE TITLE
System.ArgumentOutOfRangeException: Index was out of range

### ISSUE THREAD

**Issue by HK1GTARP** [adikanchukov/los-santos-v#26]
I don't know why, but this required line of code causes an error while starting the server:

https://github.com/warxander/los-santos-v/blob/6e9be0f75e4daaffac12d947e7378758780e7fca/resources/%5Blos-santos-v%5D/lsv-main/server/session.lua#L278

![bug](https://user-images.githubusercontent.com/74354832/99874618-62ca6780-2be1-11eb-814d-6fc2edbc5bbc.PNG)

**Comment by warxander** [comment]
Will be fixed in next public release.
Thanks!

**Comment by warxander** [comment]
Fixed in 5e9a8fb
