### ISSUE TITLE
mrp-missions

### ISSUE THREAD

**Issue by IvlevAleksandr** [adikanchukov/los-santos-v#28]
Hi! Here recently came across a mission, very cool. Can I add them? link https://github.com/ddraigcymraeg/mrp-missions,
five m forum https://forum.cfx.re/t/release-crackdown-missions-system-v3-github-for-your-own-missions/961763

**Comment by warxander** [comment]
Hi,

You can't add them without proper integration, but I think it would be better idea to implement something similar from scratch.
Thank you for suggestion, I will check it later!
