### ISSUE TITLE
Gameplay: Weapon/cash cycle for new players

### ISSUE THREAD

**Issue by blattersturm** [adikanchukov/los-santos-v#4]
Currently it is problematic for new players to get enough cash to get an inventory of weapons, especially when pistols run out, and weapon stores are (common) places for enemies to camp.

There's a few ways I'm thinking that this can be resolved without breaking gameplay too much:
* 'Hidden package' collectibles like SP/classical GTA titles, containing a small amount of cash, hidden in obvious places that an exploration run around the map should be able to find.
* A number of hidden 'fixed' weapon pickups, again reminiscent of classical GTA titles, allowing new players to make a run for *free* weapons.
* Killed players _should_ drop ammo of a typical ammo type, perhaps?
* A minimal amount of spawn ammo for the default pistol, so that players will _always_ have some ammunition?

I'd be willing to implement at least some features and provide a PR, but I'm not sure on the policy as to pull request review for gameplay concepts. 😕

**Comment by blattersturm** [comment]
I just noticed that default pistol ammo is already $0, but players have a tendency to camp out the weapon stores.

Perhaps, slightly ironically, disable weapons when inside them? That might move the issue to people camping out the _entrances_, however.

**Comment by warxander** [comment]
- As you mentioned, pistol rounds are free.
- Ammu-Nation is also available through Interaction Menu.

I love `Hidden packages` idea.
It could also contains a funny message or a famous quote.
We could collect them from LSV/FiveM community.
And there could be a tracker of collected packages as well.

I will think about ammo drops and hidden weapons.
Thank you for suggestions, I appreciate it!
