### ISSUE TITLE
Gameplay: Jobs should be 'predictable'

### ISSUE THREAD

**Issue by blattersturm** [adikanchukov/los-santos-v#5]
Currently in the [new job system](https://github.com/warxander/los-santos-v/commit/0d13f159292550cac5988b985f8ef94e35472ccd), there's a number of fixed (and nice!) mission starts placed around the map.

However, as they still start a _random_ job, this makes planning ahead for players fairly difficult. It might be a decent idea that the job markers (based on a global server-side seed, cycling every _x_ hours like in GTAO?) should each start a specific job, which also would be marked on the blip's display text, and potentially a mission scaleform at the job start.

**Comment by warxander** [comment]
Added in 67ec96e69fd7d299162a88500be2487ca3946f57
Thanks.
